language: python
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: puUzyzQ4db94T41zViBCJT8xLxEtxAof/Uam/26IRSKj0L02SUmOv4J9+rdWxbZkhhfL8ZOXc+YHXldHKlyAVFGPaqexesRpx4eLo1VpOG5LfVy13pNIX0Vxf0EVwu40y9gUHEmMSAO1N65ay5RMLDEph40h+Jo9VZdz6bwPvaQ7jSMTvvdBkhXtwFgKIXK85afnCpOYpMoX7ihUOooutXDdhuOpa+qBi8C0Yv8HJdjg5FUX7CYyjsdLwkTCkOMLNzYnstD8S6canxLjGmhj/SP3+t6H4GFqS0+WaSfgvIQI79KlPq9xMNbo8q/fSrcoMiJB97h01dVpdjSjw+ZGAvRZHn/836/2orihGjeCDfnNeI3d6UuJMylTqzQZc56uJuAylm9GgcJ5jD7GBOS5I6dO5bY9HSk5e/iX2e5QMhCsvAN+V+LcaB4D+v11jU3oLelb0X6UyWPJP07R710uPNzg6zQ47qF5Z1D5p9eH6YusJ3GL+GEiIPhoaK/AHm40pLXnEYjCCUd1G9XP0HjWwO3nF4zcYlNxLHqwX3dK8qVjWMyDs0JtkgfOF01hJMEw2RVzOVid/nutBvxKxzb7OFNZ8MrnwjSRHB3sTzBHuWpPPphplCTm/Y39llVg3W5FhMVnytIWjnEtCHTsgu0wXX94Ix4xP5ygb9qlXLsv0us=
    app: naive-bayes-flask-app
  
notifications:
  email:
  - gilbertadjei800@gmail.com
