language: python
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: Hy/pqsm8y6u/pZNRqVGoXzQgpPHyTlG327R0ytr5mYDwkhwDTjTpIe8tkCpoRg9RdEhwpY6m/Ua33nRvOGtJCx7sgKgM/vmDpDFB3ogW/6uVRO+mxRJmtEQ1DAeHQaKMeTblW8TgJC0Z1zbihrc4VWwmI5cSz4UegFBK/eCLYa6dgJ+NnWzCVIfL+lNbXjfYlnMn950ukIuAv+JP+jBl00I6oDYpfqLCzYFASuxQedBHeV5cxpu6nioXEFhrx0J/QA4/x1nc8tZV8OT18jiLkZd99+whMSHk4UYbKbUhDPebEUIM9TazC/EW8hygLAfyin+SzCj4g70n36aCP85KYq0lfn392Wxod0MRAjCm5KduKCTWYvHVOzYk/BcEztrSzEQp6pLRezIz9jZCtVgu7cEk7Gn4xQGXpGFzB+xzx9t+MjVbVilZ8gxs+3IaRUh8ni34lzm1+anH7kgYbDfAyL6KgTlwwTacmFxSW4CkaeS5R04fkfs8D0qlwvvrENHldXI946KYnXaWgIfLjIA0Ux0zHE0btkxrhiak6L5S48/3c4J8nFG7f8EsaKm0nInWrsnXwGXeAlWE8ErFHWooWlOCdk/57KGT80rm2f4nDeRLoUDxDwKGu21+9qZ3E6cl9Xmfc9+XwIvim7Q01hZsgVazs/1q6NeVifg1iGYsDuA=
    app: naive-bayes-flask-app
  api_key:
    secure: puUzyzQ4db94T41zViBCJT8xLxEtxAof/Uam/26IRSKj0L02SUmOv4J9+rdWxbZkhhfL8ZOXc+YHXldHKlyAVFGPaqexesRpx4eLo1VpOG5LfVy13pNIX0Vxf0EVwu40y9gUHEmMSAO1N65ay5RMLDEph40h+Jo9VZdz6bwPvaQ7jSMTvvdBkhXtwFgKIXK85afnCpOYpMoX7ihUOooutXDdhuOpa+qBi8C0Yv8HJdjg5FUX7CYyjsdLwkTCkOMLNzYnstD8S6canxLjGmhj/SP3+t6H4GFqS0+WaSfgvIQI79KlPq9xMNbo8q/fSrcoMiJB97h01dVpdjSjw+ZGAvRZHn/836/2orihGjeCDfnNeI3d6UuJMylTqzQZc56uJuAylm9GgcJ5jD7GBOS5I6dO5bY9HSk5e/iX2e5QMhCsvAN+V+LcaB4D+v11jU3oLelb0X6UyWPJP07R710uPNzg6zQ47qF5Z1D5p9eH6YusJ3GL+GEiIPhoaK/AHm40pLXnEYjCCUd1G9XP0HjWwO3nF4zcYlNxLHqwX3dK8qVjWMyDs0JtkgfOF01hJMEw2RVzOVid/nutBvxKxzb7OFNZ8MrnwjSRHB3sTzBHuWpPPphplCTm/Y39llVg3W5FhMVnytIWjnEtCHTsgu0wXX94Ix4xP5ygb9qlXLsv0us=
notifications:
  email:
  - gilbertadjei800@gmail.com
